echo Pulling latest code from Github...
git pull
echo Running migrations...
/var/www/deviant/venv/bin/python manage.py migrate
echo Restarting Gunicorn...
sudo systemctl restart gunicorn 
echo Restarting Celery...
sudo systemctl restart celery
echo Restarting CeleryBeat...
sudo systemctl restart celerybeat
echo Restart complete!