# Generated by Django 4.0.2 on 2022-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dauser',
            name='deviations_count',
            field=models.IntegerField(default=0, verbose_name='DeviationsCount'),
        ),
        migrations.AlterField(
            model_name='dauser',
            name='pageview_count',
            field=models.IntegerField(default=0, verbose_name='Page ViewCount'),
        ),
        migrations.AlterField(
            model_name='dauser',
            name='watchers_count',
            field=models.IntegerField(default=0, verbose_name='WatchersCount'),
        ),
    ]
