# Generated by Django 4.0.2 on 2022-02-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_dauser_deviations_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dauser',
            name='userid',
            field=models.UUIDField(blank=True, null=True, verbose_name='DA User Id'),
        ),
    ]
