# Generated by Django 4.0.2 on 2022-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_dauser_token_user_da_userid_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='da_userid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DA User Id'),
        ),
    ]
