# Generated by Django 4.0.2 on 2022-03-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_user_da_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviationid', models.UUIDField(verbose_name='Deviation Id')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'deviation',
                'verbose_name_plural': 'deviations',
            },
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(blank=True, null=True, verbose_name='Deviation Id')),
                ('thanked', models.BooleanField(default=False, verbose_name='Thanked')),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favors', to='data.deviation')),
            ],
            options={
                'verbose_name': 'Favor',
                'verbose_name_plural': 'Favors',
            },
        ),
    ]
