# Generated by Django 4.0.3 on 2022-03-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_deviation_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dauser',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
