# Generated by Django 4.0.2 on 2022-03-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_favor_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(verbose_name='DA User Id')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'thank',
                'verbose_name_plural': 'thanks',
            },
        ),
    ]
