# Generated by Django 4.0.2 on 2022-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_thank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('DEVIATIONS', 'DEVIATIONS'), ('FAVORS', 'FAVORS')], max_length=50, null=True)),
                ('offset', models.IntegerField(verbose_name='Offset')),
                ('status', models.CharField(choices=[('ERROR', 'ERROR'), ('DONE', 'DONE')], max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'download',
                'verbose_name_plural': 'downloads',
            },
        ),
        migrations.RemoveField(
            model_name='favor',
            name='thanked',
        ),
        migrations.AddField(
            model_name='thank',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterUniqueTogether(
            name='thank',
            unique_together={('owner', 'userid')},
        ),
    ]
