# Generated by Django 4.0.2 on 2022-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_download_remove_favor_thanked_thank_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
