# Generated by Django 3.2.12 on 2022-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_delete_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='favourites',
            field=models.IntegerField(default=0, verbose_name='Favourites'),
            preserve_default=False,
        ),
    ]
