# Generated by Django 3.2.12 on 2022-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_deviation_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='fav_timestimp',
            field=models.IntegerField(default=0, verbose_name='Fav Timestamp'),
        ),
        migrations.AddField(
            model_name='favor',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
