# Generated by Django 3.2.12 on 2022-03-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20220321_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favor',
            old_name='fav_timestimp',
            new_name='fav_timestamp',
        ),
    ]
