# Generated by Django 3.2.12 on 2022-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_rename_fav_timestimp_favor_fav_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thank',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent Timestamp'),
        ),
    ]
