# Generated by Django 3.2.13 on 2022-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_thank_sent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thank',
            name='message',
            field=models.TextField(default='Thanks for the fav!', verbose_name='Message'),
        ),
    ]
