# Generated by Django 3.2.13 on 2022-04-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_competitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
