# Generated by Django 3.2.13 on 2022-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='competitors', to='data.DAUser', verbose_name='Watchers'),
        ),
    ]
