# Generated by Django 3.2.13 on 2022-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_competitor_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='competitors', to='data.DAUser', verbose_name='Watchers'),
        ),
    ]
