# Generated by Django 3.2.13 on 2022-04-16 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20220416_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COMPETITORS', 'COMPETITORS'), ('FAVOURITES', 'FAVOURITES'), ('DEVIATIONS', 'DEVIATIONS')], max_length=50, verbose_name='Task')),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('IDLE', 'IDLE')], default='IDLE', max_length=50, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'My Task',
                'verbose_name_plural': 'My Tasks',
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
