# Generated by Django 3.2.13 on 2022-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_mytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='last_ran',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Ran'),
        ),
    ]
