# Generated by Django 3.2.13 on 2022-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20220416_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='dauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dauser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
