# Generated by Django 3.2.13 on 2022-04-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20220430_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='name',
            field=models.CharField(choices=[('COMPETITORS', 'COMPETITORS'), ('FAVOURITES', 'FAVOURITES'), ('DEVIATIONS', 'DEVIATIONS'), ('COMPETITOR_WATCHERS', 'COMPETITOR_WATCHERS')], max_length=50, verbose_name='Task'),
        ),
    ]
